# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jiwoo Kum"
resume_title:                   "Aspiring AI Engineer | NLP & LLM Research"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "rmawldn@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Aspiring AI Engineer and Researcher specializing in Natural Language Processing (NLP) and Large Language Models (LLM). I am passionate about exploring the frontiers of generative AI and developing data-driven solutions for complex language tasks. Currently focusing on building practical expertise in model fine-tuning and AI-powered applications.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/goldi1204"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/share/17snfu7FhC/"
  resume_linkedin_url:          "https://www.linkedin.com/in/jiwookum"
  resume_instagram_url:         "https://www.instagram.com/gold_eras/"
  resume_website_url:           "https://goldi1204.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
